name: Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          debug: yes
          token: ${{ secrets.GITHUB_TOKEN }}

          output_action: commit
          committer_branch: metrics-renders
          committer_message: "Chore: update metrics"
 
          filename: metrics.svg

          template: repository
          repo: ${{ github.repository }}
          base: header, repositories

          plugin_lines: yes
          plugin_lines_sections: history
          plugin_lines_history_limit: 1
          plugin_lines_delay: 30